---
- name: "Installing Packages"
  package:
    name:
      - neo4j
      - gobuster
      - feroxbuster
     # - remmina
      - crowbar
      - sshuttle
      - joomscan
      - rlwrap
      - libkrb5-dev
      - krb5-user
      - krb5-pkinit
      - libldap2-dev
      - libsasl2-dev
      - libreoffice
      - liblnk-utils
      - ntpsec-ntpdate
      - jq
      - azure-cli
      - trufflehog
      - sprayhound
      - wimtools
      - wmi-client
      - xtightvncviewer
      - braa
    state: latest
  become: true
  become_method: sudo